#!/bin/sh
echo "Executing pre-commit hook..."

echo "running ktlintCheck"

./gradlew ktlintCheck
if [ $? -ne 0 ]; then
  echo "ktlint check failed, running ktlintFormat"
  ./gradlew ktlintFormat
  exit 1
fi
