name: Coverage (Kover)

on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write   # necesario para comentar en PRs

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle (with cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Test + Coverage (coverageAll)
        run: ./gradlew clean coverageAll --stacktrace

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: kover-html
          path: build/reports/kover/html

      - name: PR comment (Kover)
        if: github.event_name == 'pull_request'
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/build/reports/kover/report.xml
          title: "Kover Coverage"
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 0